### ISSUE TITLE
Update the agent on Github pages

### ISSUE THREAD

**Issue by mahmoudhossam** [UltimateHackingKeyboard/agent#1413]
[This page](http://ultimatehackingkeyboard.github.io/agent/#/about) displays a somewhat outdated version of agent (1.4.5).

The gh-pages branch needs to be brought up to speed as it hasn't received any commits for more than 8 months as of the time of this writing.

**Comment by mondalaci** [comment]
@ert78gb When resolving this issue, let's implement an auto-update mechanism for the web version which is triggered when releasing new versions (non pre-release releases).

**Comment by krokofant** [comment]
It should be enough to run `npm run deploy-gh-pages` or use the github action.

Something like:
```yaml
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: packages/uhk-web/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
```

Not sure how you'd run it only on non pre-releases.
